name: Run Selenium Tests (Gradle)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chrome, firefox ]  # Run tests on both Chrome and Firefox

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Chrome and Matching ChromeDriver
        if: matrix.browser == 'chrome'
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable wget unzip curl jq

          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          echo "Detected Chrome version: $CHROME_VERSION"

          DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" | \
                       jq -r ".versions[] | select(.version | startswith(\"$CHROME_VERSION\")) | .downloads.chromedriver[] | select(.platform == \"linux64\") | .url" | tail -1)

          if [[ -z "$DRIVER_URL" ]]; then
            echo "Error: Could not find a matching ChromeDriver version for Chrome $CHROME_VERSION"
            exit 1
          fi

          echo "Downloading ChromeDriver from: $DRIVER_URL"

          wget -q -O /tmp/chromedriver.zip "$DRIVER_URL"
          unzip /tmp/chromedriver.zip -d /tmp/
          sudo mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver --version

      - name: Install Firefox and GeckoDriver
        if: matrix.browser == 'firefox'
        run: |
          sudo apt install -y firefox
          sudo apt install -y wget tar unzip
          FIREFOX_VERSION=$(firefox --version | grep -oP '[0-9]+\.[0-9]+')
          GECKODRIVER_VERSION=$(curl -s "https://github.com/mozilla/geckodriver/releases" | grep -oP "v${FIREFOX_VERSION}[^\"]+" | head -1)
          wget "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
          tar -xvzf "geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Selenium Tests with ${{ matrix.browser }}
        run: ./gradlew test -Dbrowser=${{ matrix.browser }} --no-daemon

      - name: Upload Test Results (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: build/reports/tests/
