name: Run Selenium Tests (Gradle)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Chrome and ChromeDriver  #
        run: |
          sudo apt update
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Detected Chrome version: $CHROME_VERSION"
    
          
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build-with-downloads.json" | jq -r ".builds[\"$CHROME_VERSION\"] | .revision")
          echo "Installing ChromeDriver version: $DRIVER_VERSION"
    
          wget -q -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$DRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip /tmp/chromedriver.zip -d /tmp/
          sudo mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver --version

      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt install -y firefox
          sudo apt install -y wget tar unzip
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
          wget "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
          tar -xvzf "geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Selenium Tests
        run: ./gradlew test --no-daemon  # Runs all tests

      - name: Upload Test Results (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: build/reports/tests/
